server:
  port: 8060 #指定该eureka实例的端口号

spring:
  application:
    name: microservice-api-gateway #项目名称，尽量使用小写
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defauleZone: http://discovery:8761/eureka/  #指定注册中心地址