server:
  port: 8001 #指定该eureka实例的端口号

spring:
  application:
    name: microservice-provider-uesr #项目名称，尽量使用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                     #指定数据源
    platform: h2                  #指定数据源类型
    schema: classpath:schema.sql  #指定h2数据库的建表脚本
    data: classpath:data.sql      #指定h2数据库的insert脚本
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defauleZone: http://discovery:8761/eureka/  #指定注册中心地址