server:
  port: 8020 #指定该eureka实例的端口号

spring:
  application:
    name: microservice-consumer-movie-feign #项目名称，尽量使用小写
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defauleZone: http://discovery:8761/eureka/  #指定注册中心地址
ribbon:
  eureka:
    enabled: true