#---------单机版----------
server:
  port: 8761 #指定该eureka实例的端口号
eureka:
  instance:
    hostname: discovery #指定该eureka实例的主机名
  client:
    register-with-eureka: false
    fecth-registry: false
    serviceUrl:
      defauleZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#---------高可用版本----------
#server:
#  port: 8762 #指定该eureka实例的端口号
#eureka:
#  instance:
#    hostname: peer2 #指定该eureka实例的主机名
#  client:
#    serviceUrl:
#      defauleZone: http://peer1:8761/eureka/ #将自己注册到peer1这个Eureka实例上