server:
  port: 8021 #指定该eureka实例的端口号

spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix #项目名称，尽量使用小写
eureka:
  instance:
    hostname: feign
    preferIpAddress: false
  client:
    serviceUrl:
      defauleZone: http://discovery:8761/eureka/  #指定注册中心地址
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true